// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeF5EBlqq40qebsHyUNyX2AcAt5osy03Y',
    appId: '1:779797669893:web:4be7c30dd3fe980f3ed46c',
    messagingSenderId: '779797669893',
    projectId: 'fir-test-d2f09',
    authDomain: 'fir-test-d2f09.firebaseapp.com',
    storageBucket: 'fir-test-d2f09.appspot.com',
    measurementId: 'G-4D2W0WK9VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nN_y0zi6h7RqOWI_H2YcvWuP-Plo7hI',
    appId: '1:779797669893:android:bb233c411136ff5b3ed46c',
    messagingSenderId: '779797669893',
    projectId: 'fir-test-d2f09',
    storageBucket: 'fir-test-d2f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzrc5QA9wibFdcu0h77v7S9iOVvcVkxo',
    appId: '1:779797669893:ios:427136bd7f2392923ed46c',
    messagingSenderId: '779797669893',
    projectId: 'fir-test-d2f09',
    storageBucket: 'fir-test-d2f09.appspot.com',
    iosClientId:
        '779797669893-dcrra9tbd4ahlqoho1fqf95fb385kd2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.earthquakeDamageAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZzrc5QA9wibFdcu0h77v7S9iOVvcVkxo',
    appId: '1:779797669893:ios:427136bd7f2392923ed46c',
    messagingSenderId: '779797669893',
    projectId: 'fir-test-d2f09',
    storageBucket: 'fir-test-d2f09.appspot.com',
    iosClientId:
        '779797669893-dcrra9tbd4ahlqoho1fqf95fb385kd2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.earthquakeDamageAssessment',
  );
}
